package nl.pim16aap2.lightkeeper.runtime.agent;

/**
 * Supported LightKeeper agent actions for runtime protocol version 1.
 */
public enum AgentAction
{
    HANDSHAKE,
    MAIN_WORLD,
    NEW_WORLD,
    EXECUTE_COMMAND,
    BLOCK_TYPE,
    SET_BLOCK,
    CREATE_PLAYER,
    REMOVE_PLAYER,
    EXECUTE_PLAYER_COMMAND,
    PLACE_PLAYER_BLOCK,
    LEFT_CLICK_BLOCK,
    RIGHT_CLICK_BLOCK,
    GET_OPEN_MENU,
    CLICK_MENU_SLOT,
    DRAG_MENU_SLOTS,
    GET_PLAYER_MESSAGES,
    WAIT_TICKS,
    GET_SERVER_TICK,
    TELEPORT_PLAYER,
    LOAD_CHUNK,
    UNLOAD_CHUNK,
    IS_CHUNK_LOADED,
    GET_PLAYER_INVENTORY,
    DROP_ITEM,
    REGISTER_EVENT_LISTENER,
    GET_CAPTURED_EVENTS,
    CLEAR_CAPTURED_EVENTS,
    UNREGISTER_EVENT_LISTENER
}
