package nl.pim16aap2.lightkeeper.runtime;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Reads runtime manifests generated by LightKeeper.
 */
public final class RuntimeManifestReader
{
    private final ObjectMapper objectMapper = new ObjectMapper()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    /**
     * Reads and validates a runtime manifest.
     *
     * @param path
     *     The path to the manifest.
     * @return The parsed runtime manifest.
     * @throws IOException
     *     When reading or parsing fails.
     */
    public RuntimeManifest read(Path path)
        throws IOException
    {
        if (!Files.isRegularFile(path))
            throw new IOException("Runtime manifest '%s' does not exist.".formatted(path));

        final RuntimeManifest manifest = objectMapper.readValue(path.toFile(), RuntimeManifest.class);
        validate(manifest);
        return manifest;
    }

    private static void validate(RuntimeManifest manifest)
        throws IOException
    {
        if (manifest.serverType() == null || manifest.serverType().isBlank())
            throw new IOException("Runtime manifest field 'serverType' is missing or blank.");
        if (manifest.serverVersion() == null || manifest.serverVersion().isBlank())
            throw new IOException("Runtime manifest field 'serverVersion' is missing or blank.");
        if (manifest.cacheKey() == null || manifest.cacheKey().isBlank())
            throw new IOException("Runtime manifest field 'cacheKey' is missing or blank.");
        if (manifest.serverDirectory() == null || manifest.serverDirectory().isBlank())
            throw new IOException("Runtime manifest field 'serverDirectory' is missing or blank.");
        if (manifest.serverJar() == null || manifest.serverJar().isBlank())
            throw new IOException("Runtime manifest field 'serverJar' is missing or blank.");
        if (manifest.udsSocketPath() == null || manifest.udsSocketPath().isBlank())
            throw new IOException("Runtime manifest field 'udsSocketPath' is missing or blank.");
        if (manifest.agentAuthToken() == null || manifest.agentAuthToken().isBlank())
            throw new IOException("Runtime manifest field 'agentAuthToken' is missing or blank.");
        if (manifest.runtimeProtocolVersion() == null || manifest.runtimeProtocolVersion().isBlank())
            throw new IOException("Runtime manifest field 'runtimeProtocolVersion' is missing or blank.");
        if (manifest.agentCacheIdentity() == null || manifest.agentCacheIdentity().isBlank())
            throw new IOException("Runtime manifest field 'agentCacheIdentity' is missing or blank.");

        for (RuntimeManifest.PreloadedWorld preloadedWorld : manifest.preloadedWorlds())
        {
            if (preloadedWorld.name() == null || preloadedWorld.name().isBlank())
                throw new IOException("Runtime manifest contains preloaded world with missing name.");
            if (preloadedWorld.environment() == null || preloadedWorld.environment().isBlank())
                throw new IOException("Runtime manifest preloaded world '%s' is missing environment."
                    .formatted(preloadedWorld.name()));
            if (preloadedWorld.worldType() == null || preloadedWorld.worldType().isBlank())
                throw new IOException("Runtime manifest preloaded world '%s' is missing worldType."
                    .formatted(preloadedWorld.name()));
        }
    }
}
