package nl.pim16aap2.lightkeeper.runtime;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Writes runtime manifests generated by LightKeeper.
 */
public final class RuntimeManifestWriter
{
    private final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Writes a runtime manifest to the provided path.
     *
     * @param runtimeManifest
     *     The manifest to write.
     * @param path
     *     The output path.
     * @throws IOException
     *     When writing fails.
     */
    public void write(RuntimeManifest runtimeManifest, Path path)
        throws IOException
    {
        objectMapper.writeValue(path.toFile(), runtimeManifest);
    }
}
