name: Test, build, and upload LightKeeper
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the project
        run: mvn --batch-mode clean test install verify checkstyle:checkstyle pmd:check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: lightkeeper-report-aggregate/target/site/jacoco-aggregate
          token: ${{ secrets.CODECOV_TOKEN }}
