name: Deploy snapshot to EldoNexus

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS"
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  MAVEN_GPG_KEY_FINGERPRINT: ${{ secrets.MAVEN_GPG_KEY_FINGERPRINT }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21 + GPG
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          server-id: eldonexus-snapshots
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD

      - name: Deploy snapshot
        run: |
          mvn --batch-mode --show-version --no-transfer-progress \
            -Psign \
            -Dgpg.keyname=${MAVEN_GPG_KEY_FINGERPRINT} \
            -DskipTests \
            deploy
