package nl.pim16aap2.lightkeeper.framework;

import nl.pim16aap2.lightkeeper.framework.internal.DefaultLightkeeperFramework;

import java.nio.file.Path;

/**
 * Factory for creating framework instances from runtime manifests.
 */
public final class Lightkeeper
{
    private Lightkeeper()
    {
    }

    /**
     * Creates and starts a framework instance.
     *
     * @param runtimeManifestPath
     *     Path to the runtime manifest generated by {@code prepare-server}.
     * @return A started framework.
     */
    public static LightkeeperFramework start(Path runtimeManifestPath)
    {
        return DefaultLightkeeperFramework.start(runtimeManifestPath);
    }
}
